### PR TITLE
Added motor_enabled listener & bugfixes (updated)

### PR DESCRIPTION
**Pull request by 0xD0M1M0**
- added favicon
- commented out the status post on not existing element-id
- added console log for websocket server
- introduced motor_listener to enable Motor on/off toogle on web interface
- closed body tag

### CODE REVIEW

**Comment by 0xD0M1M0** [comment]
Any feedback?

**Comment by 0xD0M1M0** [comment]
Dear ESA-PRL,
@diogopbrandao, @martinazkarate, @levingerdes,

it is not an easy commitment to support this project. Basically ideas from the community are staying unreviewed and uncommented. Obivous bugs stay in the software and new ExoMy-Owners are suffering from the same problems again and again. I know working for ESA is a hard business and this project is not your main task, but at least dedicate some time to this project and value the community you triggered with this project.

This pull request is a simple fix to a webgui and a value in a motor config. The review time for this is less than 10 minutes. There is no need to keep it unreviewed for almost a year. I am not requesting any IRR, TRR, FRR nor TRB or anything else of your daily business, I am asking you to support this community or give the community more power to implement ideas.

Best regards

**Comment by 0xD0M1M0** [comment]
Dear ESA-PRL,
@diogopbrandao, @martinazkarate, @levingerdes,
any updates on the merging process?
Best regards

**Comment by levingerdes** [comment]
Dear @0xD0M1M0 ,

Unfortunately we could not find any maintenance support for ExoMy from inside ESA. We were hesitant to state this prematurely while we were still contacting different sections and individuals, hoping to have official support for this. It was also not deemed OK to give full permissions to people outside of ESA without double checking all commits.

At this point, we believe it only honest to archive the ExoMy repositories (so that the published links don't link to empty pages) and because you are clearly the most active member of the ExoMy community we'd like to link to your forked repositories. We hope that by linking to your forks in the description of our repos, people will find their way to your maintained repositories. Are you okay with being featured like that?

Best regards and thanks for all your efforts

**Comment by 0xD0M1M0** [comment]
I close this pull request. I integrated this function in https://github.com/0xD0M1M0/ExoMy_Software/tree/official_main. All further updates from me are there.

**Pull request closed without merging**
